name: Trigger auto deployment for greenbaum-lab-assistant-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/greenbaum-lab-assistant-app-AutoDeployTrigger-20af7e08-70c2-4150-a20f-cb1c65800208.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GREENBAUMLABASSISTANTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GREENBAUMLABASSISTANTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GREENBAUMLABASSISTANTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: greenbaumassistant.azurecr.io
          registryUsername: ${{ secrets.GREENBAUMLABASSISTANTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GREENBAUMLABASSISTANTAPP_REGISTRY_PASSWORD }}
          containerAppName: greenbaum-lab-assistant-app
          resourceGroup: ai-group
          imageToBuild: greenbaumassistant.azurecr.io/greenbaum-lab-assistant-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


